import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import Navbar from "./components/Navbar";
import { ReduxProvider } from "@/redux/provider";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata: Metadata = {
  title: "Rest Countries API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} min-h-[100vh] bg-veryLightGray`}
      >
        <ReduxProvider>
          <Navbar mode="Dark Mode" logo="Where in the world?" />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
